[package]
name = "s37"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mongodb = "2"
tokio = { version = "1", features = ["full"] }
dotenv = "0"
axum = "0"